### ISSUE TITLE
Non-standard include path

### ISSUE THREAD

**Issue by Southclaws** [RIDE-2DAY/TrafficLights#1]
https://github.com/RIDE-2DAY/TrafficLights/blob/39ed82dc0c25eb00c1f4d8296808abe660a8fde7/trafficlights.inc#L17-L18

This should be 

`#include <YSI\y_...>`

The standard way for handling dependencies is to simply have the library root on the include path - not with a subdirectory.

If you personally prefer to keep YSI in its own directory, use the `-i` compiler flag to specify an additional `#include <>` path.

**Comment by Vasily-X** [comment]
@Southclaws: that's true, usually I change them when I release something but I forgot this time! Thank you for pointing it out.
